/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int FUN = 5;
  /** RegularExpression Id. */
  int COMMA = 6;
  /** RegularExpression Id. */
  int WHILE = 7;
  /** RegularExpression Id. */
  int IF = 8;
  /** RegularExpression Id. */
  int BOOLEAN = 9;
  /** RegularExpression Id. */
  int LET = 10;
  /** RegularExpression Id. */
  int NEW = 11;
  /** RegularExpression Id. */
  int ASSIGN = 12;
  /** RegularExpression Id. */
  int REF = 13;
  /** RegularExpression Id. */
  int PRINTLN = 14;
  /** RegularExpression Id. */
  int Id = 15;
  /** RegularExpression Id. */
  int Num = 16;
  /** RegularExpression Id. */
  int LOGICALEQUAL = 17;
  /** RegularExpression Id. */
  int LOWER = 18;
  /** RegularExpression Id. */
  int LOWEROREQUAL = 19;
  /** RegularExpression Id. */
  int OR = 20;
  /** RegularExpression Id. */
  int AND = 21;
  /** RegularExpression Id. */
  int NOT = 22;
  /** RegularExpression Id. */
  int GREATER = 23;
  /** RegularExpression Id. */
  int GREATEROREQUAL = 24;
  /** RegularExpression Id. */
  int PLUS = 25;
  /** RegularExpression Id. */
  int MINUS = 26;
  /** RegularExpression Id. */
  int TIMES = 27;
  /** RegularExpression Id. */
  int DIV = 28;
  /** RegularExpression Id. */
  int LPAR = 29;
  /** RegularExpression Id. */
  int RPAR = 30;
  /** RegularExpression Id. */
  int LBRA = 31;
  /** RegularExpression Id. */
  int RBRA = 32;
  /** RegularExpression Id. */
  int EQUAL = 33;
  /** RegularExpression Id. */
  int SEMCOL = 34;
  /** RegularExpression Id. */
  int FINAL = 35;
  /** RegularExpression Id. */
  int STRING = 36;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"fn\"",
    "\",\"",
    "\"while\"",
    "\"if\"",
    "<BOOLEAN>",
    "\"let\"",
    "\"new\"",
    "\":=\"",
    "\"!\"",
    "\"println\"",
    "<Id>",
    "<Num>",
    "\"==\"",
    "\"<\"",
    "\"<=\"",
    "\"||\"",
    "\"&&\"",
    "\"~\"",
    "\">\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\";\"",
    "\";;\"",
    "<STRING>",
  };

}
