package com.monke.parser;
/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int FUN = 5;
  /** RegularExpression Id. */
  int COMMA = 6;
  /** RegularExpression Id. */
  int WHILE = 7;
  /** RegularExpression Id. */
  int IF = 8;
  /** RegularExpression Id. */
  int BOOLEAN = 9;
  /** RegularExpression Id. */
  int VAR = 10;
  /** RegularExpression Id. */
  int CONST = 11;
  /** RegularExpression Id. */
  int NEW = 12;
  /** RegularExpression Id. */
  int ASSIGN = 13;
  /** RegularExpression Id. */
  int REF = 14;
  /** RegularExpression Id. */
  int PRINTLN = 15;
  /** RegularExpression Id. */
  int ID = 16;
  /** RegularExpression Id. */
  int NUM = 17;
  /** RegularExpression Id. */
  int LOGICALEQUAL = 18;
  /** RegularExpression Id. */
  int LOWER = 19;
  /** RegularExpression Id. */
  int LOWEROREQUAL = 20;
  /** RegularExpression Id. */
  int OR = 21;
  /** RegularExpression Id. */
  int AND = 22;
  /** RegularExpression Id. */
  int NOT = 23;
  /** RegularExpression Id. */
  int GREATER = 24;
  /** RegularExpression Id. */
  int GREATEROREQUAL = 25;
  /** RegularExpression Id. */
  int PLUS = 26;
  /** RegularExpression Id. */
  int INC = 27;
  /** RegularExpression Id. */
  int MINUS = 28;
  /** RegularExpression Id. */
  int DEC = 29;
  /** RegularExpression Id. */
  int TIMES = 30;
  /** RegularExpression Id. */
  int DIV = 31;
  /** RegularExpression Id. */
  int LPAR = 32;
  /** RegularExpression Id. */
  int RPAR = 33;
  /** RegularExpression Id. */
  int LBRA = 34;
  /** RegularExpression Id. */
  int RBRA = 35;
  /** RegularExpression Id. */
  int EQUAL = 36;
  /** RegularExpression Id. */
  int SEMCOL = 37;
  /** RegularExpression Id. */
  int FINAL = 38;
  /** RegularExpression Id. */
  int STRING = 39;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"fn\"",
    "\",\"",
    "\"while\"",
    "\"if\"",
    "<BOOLEAN>",
    "\"var\"",
    "\"const\"",
    "\"new\"",
    "\":=\"",
    "\"!\"",
    "\"println\"",
    "<ID>",
    "<NUM>",
    "\"==\"",
    "\"<\"",
    "\"<=\"",
    "\"||\"",
    "\"&&\"",
    "\"~\"",
    "\">\"",
    "\">=\"",
    "\"+\"",
    "\"++\"",
    "\"-\"",
    "\"--\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\";\"",
    "\";;\"",
    "<STRING>",
  };

}
