package com.monke.parser;
/* Generated By:JavaCC: Do not edit this line. SimpleParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SimpleParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LET = 5;
  /** RegularExpression Id. */
  int BOOLEAN = 6;
  /** RegularExpression Id. */
  int ID = 7;
  /** RegularExpression Id. */
  int NUM = 8;
  /** RegularExpression Id. */
  int EQUAL = 9;
  /** RegularExpression Id. */
  int SEMCOL = 10;
  /** RegularExpression Id. */
  int FINAL = 11;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"let\"",
    "<BOOLEAN>",
    "<ID>",
    "<NUM>",
    "\"=\"",
    "\";\"",
    "\";;\"",
  };

}
